
services:
  database:
    image: postgres:16.3
    ports:
      - "5432:5432"
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    env_file:
      - ../backend/.env
    restart: always

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    env_file:
      - ../backend/.env
    command: bash -c "
      python manage.py migrate --noinput &&
      python manage.py collectstatic --noinput &&
      gunicorn mysite.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ../backend:/app
      - ./staticfiles/static:/app/docker/staticfiles/static
      - ./mediafiles:/app/docker/mediafiles
    restart: always

  nginx:
    image: nginx:1.27.0
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf.template
      - ./staticfiles/static:/app/staticfiles/static
      - ./mediafiles:/app/mediafiles
    ports:
      - "80:80"
    command: /bin/sh -c "envsubst '${DOMAIN_NAME}' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    restart: always
    depends_on:
      - backend