services:
  nginx:
    container_name: nginx-portifolio
    image: nginx:1.27.0
    volumes:
      - ./staticfiles:/usr/share/nginx/html/static
      - ./mediafiles:/usr/share/nginx/html/mediafiles
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    networks:
      - custom_network
    depends_on:
      - django

  django:
    container_name: portifolio-django
    build:
      context: ../backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    expose:
      - "8000"
    networks:
      - custom_network
    environment:
      - DJANGO_SETTINGS_MODULE=mysite.settings

  database:
    container_name: portifolio-db
    image: postgres:16.3
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    networks:
      - custom_network

networks:
  custom_network:
    driver: bridge
